/*** This file is generated by makeTickFinance.py, do not edit ***/

#ifndef tsTICKFINANCE_H
#define tsTICKFINANCE_H

#include "tsTick.h"
#include <stdio.h>

/** Finance domain tick types, see tsTickType. */
enum
{
    tsTickTypeLast = tsTickTypeFirst-1,

    tsTickType_Price,
    tsTickType_Volume,
    tsTickType_PriceVolume,
    tsTickType_Bid,
    tsTickType_Ask,
    tsTickType_BidAsk,
    tsTickType_Recap,

    tsTickTypeCount
};

class tsTickFactoryFinance : public tsTickFactory
{
    virtual int  serializedTailSize(const tsTick& tick) const;
    virtual void serializeTail(const tsTick* pTick, char* pBuf) const;
    virtual void unserializeTail(const char* pBuf, tsTick* pTick) const;
    virtual std::string strTail(const tsTick* pTick) const;
};


struct tsTickPrice : tsTick
{
    double mPrice;
    bbU32 mOpt;

    tsTickPrice() :
        mPrice(0),
        mOpt(0),
    tsTick(tsTickType_Price) {}

    tsTickPrice(const tsObjID& objID) :
        mPrice(0),
        mOpt(0),
    tsTick(objID, tsTickType_Price) {}

    tsTickPrice(const tsObjID& objID, double price, bbU32 opt) :
        mPrice(price),
        mOpt(opt),
    tsTick(objID, tsTickType_Price) {}

    inline void setPrice(double price) { mPrice = price; }
    inline double price() const { return mPrice; }
    inline void setOpt(bbU32 opt) { mOpt = opt; }
    inline bbU32 opt() const { return mOpt; }

    static const int tailSize = 12;
    void serializeTail(char* pBuf) const;
    void unserializeTail(const char* pBuf);
    std::string strTail() const;
};

struct tsTickVolume : tsTick
{
    bbU64 mVolume;
    bbU32 mOpt;

    tsTickVolume() :
        mVolume(0),
        mOpt(0),
    tsTick(tsTickType_Volume) {}

    tsTickVolume(const tsObjID& objID) :
        mVolume(0),
        mOpt(0),
    tsTick(objID, tsTickType_Volume) {}

    tsTickVolume(const tsObjID& objID, bbU64 volume, bbU32 opt) :
        mVolume(volume),
        mOpt(opt),
    tsTick(objID, tsTickType_Volume) {}

    inline void setVolume(bbU64 volume) { mVolume = volume; }
    inline bbU64 volume() const { return mVolume; }
    inline void setOpt(bbU32 opt) { mOpt = opt; }
    inline bbU32 opt() const { return mOpt; }

    static const int tailSize = 12;
    void serializeTail(char* pBuf) const;
    void unserializeTail(const char* pBuf);
    std::string strTail() const;
};

struct tsTickPriceVolume : tsTick
{
    double mPrice;
    bbU64 mVolume;
    bbU32 mOpt;

    tsTickPriceVolume() :
        mPrice(0),
        mVolume(0),
        mOpt(0),
    tsTick(tsTickType_PriceVolume) {}

    tsTickPriceVolume(const tsObjID& objID) :
        mPrice(0),
        mVolume(0),
        mOpt(0),
    tsTick(objID, tsTickType_PriceVolume) {}

    tsTickPriceVolume(const tsObjID& objID, double price, bbU64 volume, bbU32 opt) :
        mPrice(price),
        mVolume(volume),
        mOpt(opt),
    tsTick(objID, tsTickType_PriceVolume) {}

    inline void setPrice(double price) { mPrice = price; }
    inline double price() const { return mPrice; }
    inline void setVolume(bbU64 volume) { mVolume = volume; }
    inline bbU64 volume() const { return mVolume; }
    inline void setOpt(bbU32 opt) { mOpt = opt; }
    inline bbU32 opt() const { return mOpt; }

    static const int tailSize = 20;
    void serializeTail(char* pBuf) const;
    void unserializeTail(const char* pBuf);
    std::string strTail() const;
};

struct tsTickBid : tsTick
{
    double mPrice;
    bbU64 mVolume;
    bbU32 mOpt;

    tsTickBid() :
        mPrice(0),
        mVolume(0),
        mOpt(0),
    tsTick(tsTickType_Bid) {}

    tsTickBid(const tsObjID& objID) :
        mPrice(0),
        mVolume(0),
        mOpt(0),
    tsTick(objID, tsTickType_Bid) {}

    tsTickBid(const tsObjID& objID, double price, bbU64 volume, bbU32 opt) :
        mPrice(price),
        mVolume(volume),
        mOpt(opt),
    tsTick(objID, tsTickType_Bid) {}

    inline void setPrice(double price) { mPrice = price; }
    inline double price() const { return mPrice; }
    inline void setVolume(bbU64 volume) { mVolume = volume; }
    inline bbU64 volume() const { return mVolume; }
    inline void setOpt(bbU32 opt) { mOpt = opt; }
    inline bbU32 opt() const { return mOpt; }

    static const int tailSize = 20;
    void serializeTail(char* pBuf) const;
    void unserializeTail(const char* pBuf);
    std::string strTail() const;
};

struct tsTickAsk : tsTick
{
    double mPrice;
    bbU64 mVolume;
    bbU32 mOpt;

    tsTickAsk() :
        mPrice(0),
        mVolume(0),
        mOpt(0),
    tsTick(tsTickType_Ask) {}

    tsTickAsk(const tsObjID& objID) :
        mPrice(0),
        mVolume(0),
        mOpt(0),
    tsTick(objID, tsTickType_Ask) {}

    tsTickAsk(const tsObjID& objID, double price, bbU64 volume, bbU32 opt) :
        mPrice(price),
        mVolume(volume),
        mOpt(opt),
    tsTick(objID, tsTickType_Ask) {}

    inline void setPrice(double price) { mPrice = price; }
    inline double price() const { return mPrice; }
    inline void setVolume(bbU64 volume) { mVolume = volume; }
    inline bbU64 volume() const { return mVolume; }
    inline void setOpt(bbU32 opt) { mOpt = opt; }
    inline bbU32 opt() const { return mOpt; }

    static const int tailSize = 20;
    void serializeTail(char* pBuf) const;
    void unserializeTail(const char* pBuf);
    std::string strTail() const;
};

struct tsTickBidAsk : tsTick
{
    double mPriceBid;
    double mPriceAsk;
    bbU32 mOpt;

    tsTickBidAsk() :
        mPriceBid(0),
        mPriceAsk(0),
        mOpt(0),
    tsTick(tsTickType_BidAsk) {}

    tsTickBidAsk(const tsObjID& objID) :
        mPriceBid(0),
        mPriceAsk(0),
        mOpt(0),
    tsTick(objID, tsTickType_BidAsk) {}

    tsTickBidAsk(const tsObjID& objID, double priceBid, double priceAsk, bbU32 opt) :
        mPriceBid(priceBid),
        mPriceAsk(priceAsk),
        mOpt(opt),
    tsTick(objID, tsTickType_BidAsk) {}

    inline void setPriceBid(double priceBid) { mPriceBid = priceBid; }
    inline double priceBid() const { return mPriceBid; }
    inline void setPriceAsk(double priceAsk) { mPriceAsk = priceAsk; }
    inline double priceAsk() const { return mPriceAsk; }
    inline void setOpt(bbU32 opt) { mOpt = opt; }
    inline bbU32 opt() const { return mOpt; }

    static const int tailSize = 20;
    void serializeTail(char* pBuf) const;
    void unserializeTail(const char* pBuf);
    std::string strTail() const;
};

struct tsTickRecap : tsTick
{
    double mOpen;
    double mHigh;
    double mLow;
    double mClose;
    bbU64 mVolume;
    bbU64 mOpenInt;
    bbU32 mOpt;

    tsTickRecap() :
        mOpen(0),
        mHigh(0),
        mLow(0),
        mClose(0),
        mVolume(0),
        mOpenInt(0),
        mOpt(0),
    tsTick(tsTickType_Recap) {}

    tsTickRecap(const tsObjID& objID) :
        mOpen(0),
        mHigh(0),
        mLow(0),
        mClose(0),
        mVolume(0),
        mOpenInt(0),
        mOpt(0),
    tsTick(objID, tsTickType_Recap) {}

    tsTickRecap(const tsObjID& objID, double open, double high, double low, double close, bbU64 volume, bbU64 openInt, bbU32 opt) :
        mOpen(open),
        mHigh(high),
        mLow(low),
        mClose(close),
        mVolume(volume),
        mOpenInt(openInt),
        mOpt(opt),
    tsTick(objID, tsTickType_Recap) {}

    inline void setOpen(double open) { mOpen = open; }
    inline double open() const { return mOpen; }
    inline void setHigh(double high) { mHigh = high; }
    inline double high() const { return mHigh; }
    inline void setLow(double low) { mLow = low; }
    inline double low() const { return mLow; }
    inline void setClose(double close) { mClose = close; }
    inline double close() const { return mClose; }
    inline void setVolume(bbU64 volume) { mVolume = volume; }
    inline bbU64 volume() const { return mVolume; }
    inline void setOpenInt(bbU64 openInt) { mOpenInt = openInt; }
    inline bbU64 openInt() const { return mOpenInt; }
    inline void setOpt(bbU32 opt) { mOpt = opt; }
    inline bbU32 opt() const { return mOpt; }

    static const int tailSize = 52;
    void serializeTail(char* pBuf) const;
    void unserializeTail(const char* pBuf);
    std::string strTail() const;
};

#endif

